(()=>{const root=document.documentElement,read=k=>{try{return localStorage.getItem(k)}catch{return null}},write=(k,v)=>{try{localStorage.setItem(k,v)}catch{}};root.dataset.theme=read("img-theme")||root.dataset.theme||"dark";document.body.insertAdjacentHTML("afterbegin",'<img class="league-logo-mark" src="/img-logo-soccer.svg" alt="IMG"><nav class="league-site-nav" aria-label="Primary navigation"><a href="/">Home</a><a class="active" href="/sports/">Sports</a><a href="/scores/">Scores</a><a href="/news/">News</a><a href="/odds/">Odds</a></nav><nav class="league-bottomnav" aria-label="Mobile navigation"><a href="/"><b><span class="league-navglyph league-icon-home" aria-hidden="true"></span></b>Home</a><a class="active" href="/sports/"><b><span class="league-navglyph league-icon-sports" aria-hidden="true"></span></b>Sports</a><a href="/scores/"><b><span class="league-navglyph league-icon-scores" aria-hidden="true"></span></b>Scores</a><a href="/news/"><b><span class="league-navglyph league-icon-news" aria-hidden="true"></span></b>News</a><a href="/odds/"><b><span class="league-navglyph league-icon-odds" aria-hidden="true"></span></b>Odds</a></nav>');const tools=document.createElement("div");tools.className="league-mobile-tools";const back=document.createElement("a");back.className="league-backbtn";back.href="/sports/";back.setAttribute("aria-label","Back to Sports");back.title="Back to Sports";back.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M15 5.5 8.5 12 15 18.5"/></svg>';const theme=document.createElement("button");theme.className="league-themebtn";theme.type="button";theme.setAttribute("aria-label","Switch color theme");tools.append(back,theme);document.body.append(tools);const desktop='<span class="league-theme-track" aria-hidden="true"><span class="league-theme-icon sun"><svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg></span><span class="league-theme-icon moon"><svg viewBox="0 0 24 24"><path d="M20.5 14.2A8.5 8.5 0 0 1 9.8 3.5 8.5 8.5 0 1 0 20.5 14.2Z"/></svg></span><span class="league-theme-thumb"></span></span>',mobile=()=>'<span class="league-theme-mobile-icon" aria-hidden="true">'+(root.dataset.theme==="dark"?'<svg viewBox="0 0 24 24"><circle cx="12" cy="12" r="4"/><path d="M12 2v2m0 16v2M4.9 4.9l1.4 1.4m11.4 11.4 1.4 1.4M2 12h2m16 0h2M4.9 19.1l1.4-1.4M17.7 6.3l1.4-1.4"/></svg>':'<svg viewBox="0 0 24 24"><path d="M20.5 14.2A8.5 8.5 0 0 1 9.8 3.5 8.5 8.5 0 1 0 20.5 14.2Z"/></svg>')+'</span>',isMobile=()=>matchMedia("(max-width:760px)").matches,paint=()=>{theme.innerHTML=desktop+mobile();theme.setAttribute("aria-pressed",root.dataset.theme==="light"?"true":"false");theme.title=root.dataset.theme==="dark"?"Switch to light mode":"Switch to dark mode"},setTheme=next=>{root.dataset.theme=next;write("img-theme",next);paint()};paint();

let drag=false,moved=false,suppressClick=false,dx=0,dy=0;
const clampPosition=(x,y)=>{const w=tools.offsetWidth||86,h=tools.offsetHeight||44;return{x:Math.max(6,Math.min(innerWidth-w-6,x)),y:Math.max(6,Math.min(innerHeight-h-6,y))}};
const setPos=(x,y)=>{const p=clampPosition(x,y);tools.style.left=Math.round(p.x)+"px";tools.style.top=Math.round(p.y)+"px";tools.style.right="auto";tools.style.bottom="auto"};
const restore=()=>{if(!isMobile()){tools.style.left="";tools.style.top="";tools.style.right="";tools.style.bottom="";return}let p=null;try{p=JSON.parse(read("img-league-tools-position")||"null")}catch{}if(p&&Number.isFinite(Number(p.x))&&Number.isFinite(Number(p.y)))setPos(Number(p.x),Number(p.y))};
restore();

tools.addEventListener("pointerdown",e=>{if(!isMobile())return;const r=tools.getBoundingClientRect();drag=true;moved=false;suppressClick=false;dx=e.clientX-r.left;dy=e.clientY-r.top;tools.classList.add("is-dragging");try{tools.setPointerCapture(e.pointerId)}catch{}});
tools.addEventListener("pointermove",e=>{if(!drag||!isMobile())return;const r=tools.getBoundingClientRect();const nx=e.clientX-dx,ny=e.clientY-dy;if(Math.abs(nx-r.left)>3||Math.abs(ny-r.top)>3)moved=true;if(moved){suppressClick=true;setPos(nx,ny)}});
tools.addEventListener("pointerup",()=>{if(!drag)return;drag=false;tools.classList.remove("is-dragging");if(moved){const r=tools.getBoundingClientRect();write("img-league-tools-position",JSON.stringify({x:Math.round(r.left),y:Math.round(r.top)}));setTimeout(()=>{suppressClick=false},80)}});
tools.addEventListener("pointercancel",()=>{drag=false;tools.classList.remove("is-dragging")});

back.addEventListener("click",e=>{if(suppressClick){e.preventDefault();e.stopPropagation()}});
theme.addEventListener("click",e=>{if(suppressClick){e.preventDefault();e.stopPropagation();return}setTheme(root.dataset.theme==="dark"?"light":"dark")});

addEventListener("resize",()=>{if(isMobile()){const r=tools.getBoundingClientRect();setPos(r.left,r.top)}else restore()});
})();